export { default as Blog } from "./blog/Blog.jsx";
export { default as Categories } from "./categories/Categories.jsx";
export { default as CTA } from "./cta/CTA.jsx";
export { default as Features } from "./features/Features.jsx";
export { default as Footer } from "./footer/Footer.jsx";
export { default as Header } from "./header/Header.jsx";
export { default as Navbar } from "./navbar/Navbar.jsx";
export { default as Offer } from "./offer/Offer.jsx";
export { default as Possibility } from "./possibility/Possibility.jsx";
